name : First Workflow 

on:
  push:
   branches: 
     -main
jobs:
  example-job:
     runs-on: ubuntu-latest

     steps:
       - name: Print Welcome Messaage 
         run : echo"welcome to our first git action workflow"
