on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: "Chose env"
        required: true
        default: "staging" 
        type: choice
        options:
          - staging
          - production
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application 
        run: echo "Deploying the app ..."
